---
title: "Practical Machine Learning Course Project:  Learning Algorithm for Personal Activity Monitoring"
date: "Saturday, March 21, 2015"
output: html_document
---
#   Summary

An analysis that provides a model to predict personal activity monitoring using data from health monitoring devices at [http://groupware.les.inf.puc-rio.br/har]. The training set accuracy=99%.

#   Load required packages

```{r}
    set.seed = 1987
    require(caret)
    require(randomForest)
```

#   Load Data

```{r}
    trainSet <- read.csv("C:/Dropbox/Private/R/PracticalMachineLearning/pml-training.csv", 
                        na.strings=c("NA",""))
    testSet <- read.csv("C:/Dropbox/Private/R/PracticalMachineLearning/pml-testing.csv", 
                        na.strings=c("NA",""))    
```

#   Clean Data

```{r}
    cleanTrain <- trainSet[,colSums(is.na(trainSet)) == 0]
    cleanTest <-testSet[,colSums(is.na(testSet)) == 0]
```

#   Create Training and Cross-Validation datasets
Use 70% for train and 30% for test

```{r}
    trainIndex <- createDataPartition(y = cleanTrain$classe, p=0.7,list=FALSE)
    trainSet <- cleanTrain[trainIndex,]
    crossValidationSet <- cleanTrain[-trainIndex,]
    removeIndex <- as.integer(c(1,2,3,4,5,6))
    trainSet <- trainSet[,-removeIndex]
    testSet <- cleanTest[,-removeIndex]
```

#   Training
```{r}
    myTrainControl = trainControl(method = "cv", number = 4)
    modelFit <- train(trainSet$classe ~. , data = trainSet, 
                      method="rf", trControl = myTrainControl)
    modelFit
```

#   Cross Validation
```{r}
    predicted <- predict(modelFit, crossValidationSet)
    SampleError <- sum(predicted == crossValidationSet$classe)/nrow(crossValidationSet)
```

Out of sample error is .9978

#   testSet
```{r}
    answers <- predict(modelFit, testSet)
    length(answers)
    pml_write_files = function(answers){
      n = length(answers)
      for(i in 1:n){
        filename = paste0("C:/Dropbox/Private/R/PracticalMachineLearning/problem_id_",i,".txt")
        write.table(answers[i],file=filename,quote=FALSE,row.names=FALSE,col.names=FALSE)
      }
    }
```

```{r}
    pml_write_files(answers)
```

